
package uasi.ws_gestdocente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "pub_gestdocenteSoap", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PubGestdocenteSoap {


    /**
     * 
     * @param pcodcen
     * @param pcurso
     * @param plengua
     * @param pcodest
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseAgrupaciones
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsagrupaciones")
    @WebResult(name = "wsagrupacionesResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsagrupaciones", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsagrupaciones")
    @ResponseWrapper(localName = "wsagrupacionesResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsagrupacionesResponse")
    public ArrayOfClaseAgrupaciones wsagrupaciones(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodcen", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodcen,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodconvoc
     * @param pcodest
     * @param porden
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseFechaExamenesAsi
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsfechaexamenesasi")
    @WebResult(name = "wsfechaexamenesasiResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsfechaexamenesasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsfechaexamenesasi")
    @ResponseWrapper(localName = "wsfechaexamenesasiResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsfechaexamenesasiResponse")
    public ArrayOfClaseFechaExamenesAsi wsfechaexamenesasi(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi,
        @WebParam(name = "pcodconvoc", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodconvoc,
        @WebParam(name = "porden", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String porden);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodconvoc
     * @param pcodest
     * @param porden
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseFechaExamenesAsiTotal
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsfechaexamenesasitotal")
    @WebResult(name = "wsfechaexamenesasitotalResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsfechaexamenesasitotal", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsfechaexamenesasitotal")
    @ResponseWrapper(localName = "wsfechaexamenesasitotalResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsfechaexamenesasitotalResponse")
    public ArrayOfClaseFechaExamenesAsiTotal wsfechaexamenesasitotal(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi,
        @WebParam(name = "pcodconvoc", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodconvoc,
        @WebParam(name = "porden", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String porden);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodconv
     * @param porden
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseFechaExamenesAsiNue
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsfechaexamenesasinue")
    @WebResult(name = "wsfechaexamenesasinueResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsfechaexamenesasinue", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsfechaexamenesasinue")
    @ResponseWrapper(localName = "wsfechaexamenesasinueResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsfechaexamenesasinueResponse")
    public ArrayOfClaseFechaExamenesAsiNue wsfechaexamenesasinue(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi,
        @WebParam(name = "pcodconv", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodconv,
        @WebParam(name = "porden", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String porden);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodest
     * @param pcodconv
     * @param porden
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseFechaExamenesPlan
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsfechaexamenesplan")
    @WebResult(name = "wsfechaexamenesplanResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsfechaexamenesplan", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsfechaexamenesplan")
    @ResponseWrapper(localName = "wsfechaexamenesplanResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsfechaexamenesplanResponse")
    public ArrayOfClaseFechaExamenesPlan wsfechaexamenesplan(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodconv", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodconv,
        @WebParam(name = "porden", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String porden);

    /**
     * 
     * @param pcoddep
     * @param pcurso
     * @param plengua
     * @param pcodest
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseAsiDepto
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsasidepto")
    @WebResult(name = "wsasideptoResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsasidepto", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsasidepto")
    @ResponseWrapper(localName = "wsasideptoResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsasideptoResponse")
    public ArrayOfClaseAsiDepto wsasidepto(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcoddep", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcoddep,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseDatosAsig
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsdatosasig")
    @WebResult(name = "wsdatosasigResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsdatosasig", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsdatosasig")
    @ResponseWrapper(localName = "wsdatosasigResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsdatosasigResponse")
    public ArrayOfClaseDatosAsig wsdatosasig(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pagrupa
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseHorarioAgrp
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wshorarioagrp")
    @WebResult(name = "wshorarioagrpResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wshorarioagrp", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wshorarioagrp")
    @ResponseWrapper(localName = "wshorarioagrpResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WshorarioagrpResponse")
    public ArrayOfClaseHorarioAgrp wshorarioagrp(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pagrupa", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pagrupa);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param porden
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseHorarios
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wshorarios")
    @WebResult(name = "wshorariosResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wshorarios", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wshorarios")
    @ResponseWrapper(localName = "wshorariosResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WshorariosResponse")
    public ArrayOfClaseHorarios wshorarios(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi,
        @WebParam(name = "porden", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String porden);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseTitulosUni
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wstitulosuni")
    @WebResult(name = "wstitulosuniResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wstitulosuni", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wstitulosuni")
    @ResponseWrapper(localName = "wstitulosuniResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WstitulosuniResponse")
    public ArrayOfClaseTitulosUni wstitulosuni(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso);

    /**
     * 
     * @param pcodcen
     * @param ptipo
     * @param pcurso
     * @param plengua
     * @param psubtipo
     * @param pflgmovil
     * @param pcodest
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseDatosPlan
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsdatosplan")
    @WebResult(name = "wsdatosplanResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsdatosplan", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsdatosplan")
    @ResponseWrapper(localName = "wsdatosplanResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsdatosplanResponse")
    public ArrayOfClaseDatosPlan wsdatosplan(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest,
        @WebParam(name = "ptipo", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String ptipo,
        @WebParam(name = "psubtipo", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String psubtipo,
        @WebParam(name = "pcodcen", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodcen,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pflgmovil", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pflgmovil);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClasePlanesAsig
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsplanesasig")
    @WebResult(name = "wsplanesasigResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsplanesasig", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsplanesasig")
    @ResponseWrapper(localName = "wsplanesasigResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsplanesasigResponse")
    public ArrayOfClasePlanesAsig wsplanesasig(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi);

    /**
     * 
     * @param pcoddep
     * @param pcurso
     * @param plengua
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClasePlanesDep
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsplanesdep")
    @WebResult(name = "wsplanesdepResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsplanesdep", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsplanesdep")
    @ResponseWrapper(localName = "wsplanesdepResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsplanesdepResponse")
    public ArrayOfClasePlanesDep wsplanesdep(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcoddep", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcoddep);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseDptoAsig
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsdptoasig")
    @WebResult(name = "wsdptoasigResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsdptoasig", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsdptoasig")
    @ResponseWrapper(localName = "wsdptoasigResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsdptoasigResponse")
    public ArrayOfClaseDptoAsig wsdptoasig(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi);

    /**
     * 
     * @param pcoddep
     * @param pcurso
     * @param plengua
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseAreasDpto
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsareasdpto")
    @WebResult(name = "wsareasdptoResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsareasdpto", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsareasdpto")
    @ResponseWrapper(localName = "wsareasdptoResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsareasdptoResponse")
    public ArrayOfClaseAreasDpto wsareasdpto(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcoddep", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcoddep);

    /**
     * 
     * @param pcodcen
     * @param pcoddep
     * @param plengua
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseDptoCen
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsdptocen")
    @WebResult(name = "wsdptocenResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsdptocen", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsdptocen")
    @ResponseWrapper(localName = "wsdptocenResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsdptocenResponse")
    public ArrayOfClaseDptoCen wsdptocen(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcodcen", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodcen,
        @WebParam(name = "pcoddep", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcoddep);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodest
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseAsiPlan
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsasiplan")
    @WebResult(name = "wsasiplanResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsasiplan", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsasiplan")
    @ResponseWrapper(localName = "wsasiplanResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsasiplanResponse")
    public ArrayOfClaseAsiPlan wsasiplan(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodest", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodest);

    /**
     * 
     * @param plengua
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseCalificaciones
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wscalificaciones")
    @WebResult(name = "wscalificacionesResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wscalificaciones", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wscalificaciones")
    @ResponseWrapper(localName = "wscalificacionesResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WscalificacionesResponse")
    public ArrayOfClaseCalificaciones wscalificaciones(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pidgrupo
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseConvocatorias
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsconvocatorias")
    @WebResult(name = "wsconvocatoriasResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsconvocatorias", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsconvocatorias")
    @ResponseWrapper(localName = "wsconvocatoriasResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsconvocatoriasResponse")
    public ArrayOfClaseConvocatorias wsconvocatorias(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi,
        @WebParam(name = "pidgrupo", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pidgrupo);

    /**
     * 
     * @param pcurso
     * @param plengua
     * @param pcodasi
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseGrupoAsi
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsgruposasi")
    @WebResult(name = "wsgruposasiResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsgruposasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsgruposasi")
    @ResponseWrapper(localName = "wsgruposasiResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsgruposasiResponse")
    public ArrayOfClaseGrupoAsi wsgruposasi(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "pcodasi", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcodasi);

    /**
     * 
     * @param ptipoflujo
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseConveMovilidad
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wsconvemovilidad")
    @WebResult(name = "wsconvemovilidadResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wsconvemovilidad", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wsconvemovilidad")
    @ResponseWrapper(localName = "wsconvemovilidadResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WsconvemovilidadResponse")
    public ArrayOfClaseConveMovilidad wsconvemovilidad(
        @WebParam(name = "ptipoflujo", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String ptipoflujo);

    /**
     * 
     * @param pcurso
     * @param ptipocurso
     * @param plengua
     * @return
     *     returns uasi.ws_gestdocente.ArrayOfClaseTitulosPropiosUni
     */
    @WebMethod(action = "http://UASI/WS_GESTDOCENTE.wsdl/wstitulospropiosuni")
    @WebResult(name = "wstitulospropiosuniResult", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
    @RequestWrapper(localName = "wstitulospropiosuni", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.Wstitulospropiosuni")
    @ResponseWrapper(localName = "wstitulospropiosuniResponse", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", className = "uasi.ws_gestdocente.WstitulospropiosuniResponse")
    public ArrayOfClaseTitulosPropiosUni wstitulospropiosuni(
        @WebParam(name = "plengua", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String plengua,
        @WebParam(name = "pcurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String pcurso,
        @WebParam(name = "ptipocurso", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl")
        String ptipocurso);

}
