
package uasi.ws_gestdocente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "pub_gestdocente", targetNamespace = "http://UASI/WS_GESTDOCENTE.wsdl", wsdlLocation = "https://cvnet.cpd.ua.es/servicioweb/publicos/pub_gestdocente.asmx?wsdl")
public class PubGestdocente
    extends Service
{

    private final static URL PUBGESTDOCENTE_WSDL_LOCATION;
    private final static WebServiceException PUBGESTDOCENTE_EXCEPTION;
    private final static QName PUBGESTDOCENTE_QNAME = new QName("http://UASI/WS_GESTDOCENTE.wsdl", "pub_gestdocente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cvnet.cpd.ua.es/servicioweb/publicos/pub_gestdocente.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBGESTDOCENTE_WSDL_LOCATION = url;
        PUBGESTDOCENTE_EXCEPTION = e;
    }

    public PubGestdocente() {
        super(__getWsdlLocation(), PUBGESTDOCENTE_QNAME);
    }

    public PubGestdocente(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBGESTDOCENTE_QNAME, features);
    }

    public PubGestdocente(URL wsdlLocation) {
        super(wsdlLocation, PUBGESTDOCENTE_QNAME);
    }

    public PubGestdocente(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBGESTDOCENTE_QNAME, features);
    }

    public PubGestdocente(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PubGestdocente(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PubGestdocenteSoap
     */
    @WebEndpoint(name = "pub_gestdocenteSoap")
    public PubGestdocenteSoap getPubGestdocenteSoap() {
        return super.getPort(new QName("http://UASI/WS_GESTDOCENTE.wsdl", "pub_gestdocenteSoap"), PubGestdocenteSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PubGestdocenteSoap
     */
    @WebEndpoint(name = "pub_gestdocenteSoap")
    public PubGestdocenteSoap getPubGestdocenteSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://UASI/WS_GESTDOCENTE.wsdl", "pub_gestdocenteSoap"), PubGestdocenteSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBGESTDOCENTE_EXCEPTION!= null) {
            throw PUBGESTDOCENTE_EXCEPTION;
        }
        return PUBGESTDOCENTE_WSDL_LOCATION;
    }

}
